ALTER TABLE APP.REPORTINSTANCEPOINTS
ADD COLUMN scatterChart CHAR(1);
ALTER TABLE APP.REPORTINSTANCEPOINTS
ADD COLUMN plotTitle VARCHAR(50);
ALTER TABLE APP.REPORTINSTANCEPOINTS
ADD COLUMN xAxisTitle VARCHAR(50);
ALTER TABLE APP.REPORTINSTANCEPOINTS
ADD COLUMN yAxisTitle VARCHAR(50);
ALTER TABLE APP.REPORTINSTANCEPOINTS
ADD COLUMN referenceLine DOUBLE;